AdvertisementApp.UI/Controllers/AdvertisementController.cs
using AdvertisementApp.Business.Interfaces;
using AdvertisementApp.Dto;
using AdvertisementApp.UI.Extensions;
using AdvertisementApp.UI.Models;
using AdvertisimentApp;
using AdvertisimentApp.Common.Enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;

namespace AdvertisementApp.UI.Controllers
{
    public class AdvertisementController : Controller
    {
        private readonly IAppUserService _userService;
        private readonly IAdvertisementAppUserService _advertisementAppUserService;

        public AdvertisementController(IAppUserService userService, IAdvertisementAppUserService advertisementAppUserService)
        {
            _userService = userService;
            _advertisementAppUserService = advertisementAppUserService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Member")]
        public async Task<IActionResult> Send(int AdvertisementId)
        {

            var userId = int.Parse((User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)).Value);
            var userResponse = await _userService.GetByIdAsync<AppUserListDto>(userId);

            ViewBag.Gender = userResponse.Data.GenderId;

            var items = Enum.GetValues(typeof(MilitaryStatusType)); // oluşturduğumuz enumları burada tanımladık
            var list = new List<MilitarySatusListDto>(); // enumları liste içine atmak için liste tanımladık

            foreach (int item in items)
            {
                list.Add(new MilitarySatusListDto
                {
                    Id = item,
                    Defination = Enum.GetName(typeof(MilitaryStatusType), item),
                });

            }

            ViewBag.MilitaryStatus = new SelectList(list, "Id", "Defination");


            return View(new AdvertisementAppUserCreateModel
            {
                AdvertisementId = AdvertisementId,
                AppUserId = userId,

            });
        }


        [Authorize(Roles = "Member")]
        [HttpPost]
        public async Task<IActionResult> Send(AdvertisementAppUserCreateModel model)
        {
            AdvertisementAppUserCreateDto dto = new();

            if (model.CvFile != null)
            {
                var filename = Guid.NewGuid().ToString();
                var extName = Path.GetExtension(model.CvFile.FileName).ToLower();
                string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "cvFiles", filename + extName);
                var stream = new FileStream(path, FileMode.Create);
                await model.CvFile.CopyToAsync(stream);
                dto.CvPath = path;
            }

            dto.AdvertisementAppUserStatusId = model.AdvertisementAppUserStatusId;
            dto.AdvertisementId = model.AdvertisementId;
            dto.AppUserId = model.AppUserId;
            dto.EndDate = model.EndDate;
            dto.MilitarySatusId = model.MilitarySatusId;
            dto.WorkExperience = model.WorkExperience;

            var response = await _advertisementAppUserService.CreateAsync(dto);

            if (response.ResponseType == ResponseType.ValidationError)
            {
                foreach (var error in response.ValidationErrors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                    var userId = int.Parse((User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)).Value);
                    var userResponse = await _userService.GetByIdAsync<AppUserListDto>(userId);

                    ViewBag.Gender = userResponse.Data.GenderId;
                    var items = Enum.GetValues(typeof(MilitaryStatusType)); // oluşturduğumuz enumları burada tanımladık
                    var list = new List<MilitarySatusListDto>(); // enumları liste içine atmak için liste tanımladık

                    foreach (int item in items)
                    {
                        list.Add(new MilitarySatusListDto
                        {
                            Id = item,
                            Defination = Enum.GetName(typeof(MilitaryStatusType), item),
                        });

                    }

                    ViewBag.MilitaryStatus = new SelectList(list, "Id", "Defination");
                }
                return View(model);
            }
            else
            {
                return RedirectToAction("HumanResorce", "Home");
            }
        }

        [Authorize(Roles ="Admin")] // rolun içerisinde admin olan kişi buraya girebilsin
        public async Task< IActionResult> List()
        {

          var list= await _advertisementAppUserService.GetList(AdvertisementAppUserStatusType.Başvurdu);

            return View(list);
        }

        [Authorize(Roles = "Admin")]
        public async Task< IActionResult> SetStatus(int advertismentAppUserId, AdvertisementAppUserStatusType type)
        {
           await _advertisementAppUserService.SetStatusAsync(advertismentAppUserId, type);
            return RedirectToAction("List");
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> ApprovedList()
        {
            var list = await _advertisementAppUserService.GetList(AdvertisementAppUserStatusType.Mülakat);

            return View(list);

        }[Authorize(Roles = "Admin")]
        public async Task<IActionResult> RejectedList()
        {
            var list = await _advertisementAppUserService.GetList(AdvertisementAppUserStatusType.Olumsuz);

            return View(list);

        }



    }
}

AdvertisementApp.UI/Controllers/ApplicationController.cs
using AdvertisementApp.Business.Interfaces;
using AdvertisementApp.Dto;
using AdvertisementApp.UI.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AdvertisementApp.UI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ApplicationController : Controller
    {
        private readonly IAdvertisementService _advertisementService;

        public ApplicationController(IAdvertisementService advertisementService)
        {
            _advertisementService = advertisementService;
        }

        public async Task<IActionResult> List()
        {
            var response = await _advertisementService.GetAllAsync();
            return this.ResponseView(response);
        }

        public IActionResult Create()
        {
            return View(new AdvertisementCreateDto());
        }

        [HttpPost]
        public async Task<IActionResult> Create(AdvertisementCreateDto dto)
        {
            var response = await _advertisementService.CreateAsync(dto);
            return this.ResponseRedirecAction(response, "List");
        }

        public async Task< IActionResult> Update(int Id)
        {
            var response = await _advertisementService.GetByIdAsync<AdvertisementUpdateDto>(Id);

            return this.ResponseView(response);
        }

        [HttpPost]
        public async Task<IActionResult> Update(AdvertisementUpdateDto dto)
        {
           var response =await _advertisementService.UpdateAsync(dto);
            return this.ResponseRedirecAction(response, "List");
        }

        public async Task<IActionResult> Remove(int Id)
        {
            var response = await _advertisementService.RemoveAsync(Id);
            return this.ResponseRedirecAction(response, "List");
        }
    }
}

AdvertisementApp.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>One Page Wonder - Start Bootstrap Template</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/css/styles.css" rel="stylesheet" />
    @RenderSection("css",false)
</head>
<body id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg @(User.Identity.IsAuthenticated && User.IsInRole("Admin")?"navbar-dark - bg-danger":"navbar-dark navbar-custom") ">
        <div class="container px-5">
            <a class="navbar-brand" href="#page-top">Ati Bilişim</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto">
                    @{
                        if (User.Identity.IsAuthenticated) // eğer kullancıı giriş yaptıysa bunları görsün diyoruz
                        {
                            if (User.IsInRole("Member"))
                            {
                                <li class="nav-item"><a class="nav-link" asp-action="HumanResorce" asp-controller="Home">İnsan Kaynakları</a></li>
                            }

                            if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item"><a class="nav-link" asp-action="List" asp-controller="Advertisement">Başvurular</a></li>
                                <li class="nav-item"><a class="nav-link" asp-action="List" asp-controller="Application">İş İlanları</a></li>
                            }


                            <li class="nav-item"><a class="nav-link" asp-action="Logout" asp-controller="Account">Çıkış Yap</a></li>
                        }
                        else // eğer kullancıı giriş yapmaıdysa bunları görsün diyoruz
                        {
                            <li class="nav-item"><a class="nav-link" asp-action="SignIn" asp-controller="Account">Giriş Yap</a></li>
                            <li class="nav-item"><a class="nav-link" asp-action="SignUp" asp-controller="Account">Kayıt Ol</a></li>
                            <li class="nav-item"><a class="nav-link" asp-action="HumanResorce" asp-controller="Home">İnsan Kaynakları</a></li>
                        }
                    }


                </ul>
            </div>
        </div>
    </nav>
    <!-- Header-->
    @RenderBody()

    <!-- Footer-->
    <footer class="py-5 bg-black">
        <div class="container px-5"><p class="m-0 text-center text-white small">Copyright &copy; Atilla Kökçü Website 2023</p></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/js/scripts.js"></script>
    @RenderSection("script",false)
</body>
</html>